version: '3'
services: 
        client:
          image: node:18
          working_dir: /app
          volumes:
            - ./client:/app
          ports:
            - "3006:3006"
          command: npm start
        
        server:
          image: node:18
          working_dir: /server
          volumes:
            - ./server:/server
          ports:
            - "3000:3000"
          command: npm start